sudo: false
language: cpp

# More complete test matrix
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.7', 'cmake', 'cmake-data']
      env: TOOLSET=g++-4.7

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.8', 'cmake', 'cmake-data']
      env: TOOLSET=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-4.9', 'cmake', 'cmake-data']
      env: TOOLSET=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-5', 'cmake', 'cmake-data']
      env: TOOLSET=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-6', 'cmake', 'cmake-data']
      env: TOOLSET=g++-6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['g++-6', 'cmake', 'cmake-data']
      env:
        - TOOLSET=g++-6
        - CPP_EXTRA_FEATURES="cxx_relaxed_constexpr"

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5', 'george-edison55-precise-backports']
          packages: ['clang-3.5', 'cmake', 'cmake-data', 'libstdc++-6-dev']
      env: TOOLSET=clang++-3.5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'george-edison55-precise-backports']
          packages: ['clang-3.6', 'cmake', 'cmake-data', 'libstdc++-6-dev']
      env: TOOLSET=clang++-3.6

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'george-edison55-precise-backports']
          packages: ['clang-3.7', 'cmake', 'cmake-data', 'libstdc++-6-dev']
      env: TOOLSET=clang++-3.7

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8', 'george-edison55-precise-backports']
          packages: ['clang-3.8', 'cmake', 'cmake-data', 'libstdc++-6-dev']
      env: TOOLSET=clang++-3.8

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9', 'george-edison55-precise-backports']
          packages: ['clang-3.9', 'cmake', 'cmake-data', 'libstdc++-6-dev']
      env: TOOLSET=clang++-3.9

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9', 'george-edison55-precise-backports']
          packages: ['clang-3.9', 'cmake', 'cmake-data', 'libstdc++-6-dev']
      env:
        - TOOLSET=clang++-3.9
        - CPP_EXTRA_FEATURES="cxx_relaxed_constexpr"

    - os: osx
      compiler: clang
      env: TOOLSET=clang++

# before_install:
#

# Prepare build
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET -DCPP_EXTRA_FEATURES=$CPP_EXTRA_FEATURES -DMAKE_INCLUDE_TESTS=ON

script:
  - make VERBOSE=1
  - ./kvasir_mpl_test
